<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#界面和基本操作" data-toc-modified-id="界面和基本操作-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>界面和基本操作</a></span></li><li><span><a href="#基本概念" data-toc-modified-id="基本概念-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>基本概念</a></span><ul class="toc-item"><li><span><a href="#输出" data-toc-modified-id="输出-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>输出</a></span></li><li><span><a href="#表达式" data-toc-modified-id="表达式-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>表达式</a></span></li><li><span><a href="#语句" data-toc-modified-id="语句-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>语句</a></span></li></ul></li><li><span><a href="#数据类型" data-toc-modified-id="数据类型-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>数据类型</a></span><ul class="toc-item"><li><span><a href="#数值与布尔型" data-toc-modified-id="数值与布尔型-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>数值与布尔型</a></span></li><li><span><a href="#字符串" data-toc-modified-id="字符串-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>字符串</a></span></li><li><span><a href="#元组（Tuple)" data-toc-modified-id="元组（Tuple)-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>元组（Tuple)</a></span></li><li><span><a href="#列表（list)" data-toc-modified-id="列表（list)-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>列表（list)</a></span></li><li><span><a href="#字典" data-toc-modified-id="字典-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>字典</a></span></li><li><span><a href="#函数、模块和库" data-toc-modified-id="函数、模块和库-3.6"><span class="toc-item-num">3.6&nbsp;&nbsp;</span>函数、模块和库</a></span></li><li><span><a href="#条件命令" data-toc-modified-id="条件命令-3.7"><span class="toc-item-num">3.7&nbsp;&nbsp;</span>条件命令</a></span></li><li><span><a href="#循环命令" data-toc-modified-id="循环命令-3.8"><span class="toc-item-num">3.8&nbsp;&nbsp;</span>循环命令</a></span><ul class="toc-item"><li><span><a href="#for语句" data-toc-modified-id="for语句-3.8.1"><span class="toc-item-num">3.8.1&nbsp;&nbsp;</span>for语句</a></span></li><li><span><a href="#While语句" data-toc-modified-id="While语句-3.8.2"><span class="toc-item-num">3.8.2&nbsp;&nbsp;</span>While语句</a></span></li></ul></li></ul></li></ul></div>

# 界面和基本操作

# 基本概念

## 输出

In [4]:
# 输出
print ('hello')

hello

In [5]:
#变量
T=(0)
print (T)
t=(5)
print(T,t)

0
0 5

## 表达式

In [8]:
#表达式
2+2

4

In [1]:
2<1

False

##  语句

In [13]:
#语句(注意区分大小写)
X= 3
Y= 2
print (X + Y)

5

In [14]:
X= 3
Y= 2
print (X) 
print (Y)

3
2

In [15]:
X= 3
Y= 2
print (X) ; print (Y)

3
2

In [29]:
#反斜杠将一条语句分成多行显示
Total = X + \
        Y + \
        5
print (Total)

10

In [3]:
#如果x是3，返回True,如果不是，返回False
x = 3
if x == 4:  #两个等号连写意为如果条件成立
    print (True) #注意大小写
else:
    print (False)

False

# 数据类型

## 数值与布尔型

In [39]:
type (1.0)

float

In [40]:
type (888)

int

In [41]:
type (True)

bool

In [2]:
type('hello')

str

In [42]:
3==3

True

In [43]:
3==4

False

## 字符串

In [44]:
'you can do it'

'you can do it'

In [45]:
"you can do it"

'you can do it'

In [46]:
'"you can do it"'

'"you can do it"'

In [47]:
"She said,'you can do it!'"

"She said,'you can do it!'"

In [48]:
#当Python无法识别引号逻辑时，需要加入转义符号(\),将缩写引号转为字符串
"I\'m working on it"

"I'm working on it"

In [51]:
print ("I\'m working on it"
      "I\'m working on it"
      "I\'m working on it")

I'm working on itI'm working on itI'm working on it

In [54]:
print ('''"I\'m working on it"
      "I\'m working on it"
      "I\'m working on it" ''') #使用三引号''' '''分行

"I'm working on it"
      "I'm working on it"
      "I'm working on it"

In [56]:
print ('''"I\'m working on it"\n"I\'m working on it""\n"I\'m working on it" ''') #使用\n分行

"I'm working on it"
"I'm working on it""
"I'm working on it"

## 元组（Tuple)

In [69]:
#Python内置数据类型：序列、集合、映射
# 序列：包含元素，元素对应位置和索引，第一个是0，第二个是1，依此类推。
#常见序列有元组和列表。元组是有序的，不可更改，用小括号创建，元组中的元素用逗号区隔，可以是数值也可以是字符串。元素的值不能修改，位置从0开始。
Tuple = (1,'Emma',2,'Mike')
print (Tuple)

(1, 'Emma', 2, 'Mike')

In [75]:
Tuple [1] #注意是中括号，Tuple第一个字母大写.返回元组中第2个元素的值

'Emma'

In [76]:
Tuple [2]

2

In [74]:
Tuple [3]

'Mike'

## 列表（list)

In [ ]:
# 元组 tuple 是不可变的对象，list是可变的对象，list可能append和extend

In [78]:
#通过从0开始的整数进行索引，使用索引可以查找特定的元素，也可以修改现有元素。
list1 = ['Emma',1,'Mike',2,'Cobi',3]
print (list1)

['Emma', 1, 'Mike', 2, 'Cobi', 3]

In [79]:
list1 [0]

'Emma'

In [84]:
list1 [1:]   #从列表中第二个元素开始直到结束

[1, 'Mike', 2, 'Cobi', 3]

In [85]:
#用append或extend函数，为列表加新元素。
#append，新元素看作一个对象整体打包添加到列表中
#extend,新元素看作一个序列，与列表中的序列合并

In [86]:
list1 = ['Emma',1,'Mike',2,'Cobi',3]
list2 = ['Siphi',4,'Lily',5,'Robert',6]
list1.append (list2)
list1

['Emma', 1, 'Mike', 2, 'Cobi', 3, ['Siphi', 4, 'Lily', 5, 'Robert', 6]]

In [87]:
list1 = ['Emma',1,'Mike',2,'Cobi',3]
list2 = ['Siphi',4,'Lily',5,'Robert',6]
list1.extend (list2)
list1

['Emma', 1, 'Mike', 2, 'Cobi', 3, 'Siphi', 4, 'Lily', 5, 'Robert', 6]

## 字典

In [ ]:
#字典是映射类型的数据，使用花括号创建，包括一系列键，每个键对应一个值，键和值之间用冒号连接。键是唯一的，值不唯一。
#字典是可变的、无序的数据组合，可以添加或移除数据项。

In [ ]:
# 创建一个空字典  
empty_dict = {}

In [11]:
# 创建一个包含键值对的字典 
mydict = {1:'Emma',2:'Mike',4:'Lily',5:'Robert'}
print (mydict.keys())  #输出字典变量dict的全部键

dict_keys([1, 2, 4, 5])

In [14]:
# 创建一个包含键值对的字典 
mydict = {1:'Emma',2:'Mike',4:'Lily',5:'Robert'}
value = mydict[1] # 访问键为1的值
print (value)

Emma

In [9]:
# 案例
my_dict = {  
    "name": "Alice",  
    "age": 30,  
    "city": "New York"  
}
value = my_dict["name"] 
print(value)

Alice

In [17]:
#通过键来修改字典中的值。
my_dict["age"] = 31
print(my_dict)

{'name': 'Alice', 'age': 31, 'city': 'New York'}

In [22]:
# 添加字典，新的键值对  
my_dict["email"] = "alice@example.com"  
print(my_dict)

{'name': 'Alice', 'age': 31, 'city': 'New York', 'email': 'alice@example.com'}

In [23]:
# 删除"email"的键值对
del my_dict["email"]    
print(my_dict)

{'name': 'Alice', 'age': 31, 'city': 'New York'}

In [ ]:
#如果访问的键不存在于字典中，Python会抛出KeyError异常。
#为避免这种情况，可以使用get()方法，它会在键不存在时返回None或指定的默认值。

In [15]:
value = my_dict.get("address")  # 键"address"不存在，返回None  
print(value)  # 输出: None  
  
value = my_dict.get("address", "No address provided")  # 返回指定的默认值  
print(value)  # 输出: No address provided

None
No address provided

In [24]:
# 遍历字典的键  
for key in my_dict:  
    print(key)  # 输出: name, city

name
age
city

In [25]:
for value in my_dict.values():  
    print(value)

Alice
31
New York

In [26]:
for key, value in my_dict.items():  
    print(key, value)

name Alice
age 31
city New York

## 函数、模块和库

In [ ]:
#内置函数 print,type，也可自行创建函数
#将代码依据一定的逻辑组织在一起就是模块，模块内包含函数、变量等。模块集合在一起就称作库或是包。
#Python内置多个标准库，也有大量第三方库。Pandas可以用于数据分析，Selenium可用于抓取网络数据。

In [5]:
import pandas as pd

C:\Users\hp\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\hp\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [6]:
pd.read_csv ('test.csv') #注意文件名称，必须是test.csv，不能是test

    list  male  female
0      1     7       2
1      2    10       1
2      3     8       2
3      4     7       3
4      5     7       2
5      6    10       0
6      7     9       1
7      8     5       5
8      9     6       4
9     10     7       3
10    11     8       1
11    12     8       2
12    13     8       2
13    14     7       3
14    15     9       1
15    16     7       3

In [7]:
pd.read_csv ('titanic.csv')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

## 条件命令

In [98]:
#符合条件执行代码，返回结果 。如果不符合判断条件，返回结果。注意书写格式有缩进
x = 10
if x ==10:  #注意冒号
    print (x)
else:    #注意冒号
    print('否')

10

In [99]:
x = 9
if x ==10:  #注意冒号
    print (x)
else:    #注意冒号
    print('否')

否

## 循环命令

In [100]:
#允许多次执行一条或多条语句。常见的循环命令有for语句和while语句。符合条件执行，不符合返回其他结果。
x = [2,4,6,8,10]   # 创建列表X，列表为序列数据
for number in (x):
    print (number)

2
4
6
8
10

### for语句

In [104]:
# for常与else连用，表示在结束循环时执行else语句。注意格式有缩进，注意英文冒号
x =  [2, 4, 6, 8, 10] 
for number in (x):
    if number < 5:
        print (number,'小于5')
    else:
        print (number,'大于或等于5')

2 小于5
4 小于5
6 大于或等于5
8 大于或等于5
10 大于或等于5

### While语句

In [112]:
#while语句用于执行循环程序，处理需要重复执行的任务，例如抓取网页数据时需要翻页，就需要用到循环语句，
#注意格式的缩进和英文冒号
X = 0
while X < 9:
    print (X, '小于9') #判断条件为X小于9
    X = X + 1   #符合条件则执行输出语句，循环命令
else:
    print(X,'大于或等于9')

0 小于9
1 小于9
2 小于9
3 小于9
4 小于9
5 小于9
6 小于9
7 小于9
8 小于9
9 大于或等于9